# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.01
default_acceleration_scaling_factor: 0.01

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.1
  gripper_left_joint:
    has_velocity_limits: true
    max_velocity: 0.050000000000000003
    has_acceleration_limits: true
    max_acceleration: 0.1
  gripper_right_joint:
    has_velocity_limits: true
    max_velocity: 0.050000000000000003
    has_acceleration_limits: true
    max_acceleration: 0.1
  linear_joint:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: true
    max_acceleration: 0.1
  shoulder_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.1