/**:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.02389
    max_hamming: 1
    z_aligned: true
    
    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false
